### ISSUE TITLE
Fluid properties

### ISSUE THREAD

**Issue by Lilin-C** [lanl/dfnWorks#11]
Hi，I have encountered some difficulty in simulating my subject with non-Newtonian fluids. And the time-varying parameters for the viscosity in the constitutive equation should be considered. It would be so appreciated if your could tell me whether and how I can make this modification.  I run dfnWorks2.3 from docker.
Thanks，
Lin

**Comment by hymanjd** [comment]
Hi Lin, 
Are you using PFLOTRAN or FEHM for the flow solver? Regardless, you should contact those communities as the issue is with those codes rather than the dfnWorks source code. 
Jeffrey

**Comment by Lilin-C** [comment]
Thank you very much.
Lin
