### ISSUE TITLE
FileNotFoundError when running TPL

### ISSUE THREAD

**Issue by yingtaohu** [lanl/dfnWorks#12]
Hi,
    When I running the TPL simulation, there is a problem I can't deal with. The following is the description of the issue:
"lagrit.define_zones()
File "/home/dfnWorks/pydfnworks/pydfnworks/dfnGen/meshing/lagrit_scripts_poisson_disc.py", line 884, in define_zones
fzone = open("boundary_%s.zone" % f, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'boundary_bottom.zone'".
   For the simple DFN model, it runs OK. However, for complex DFN model, there is a bug. So, is this something about the DFN model ?
PS: The attach file is the generated DFN model in my study.

![DFN model](https://user-images.githubusercontent.com/34232470/101557046-237c8300-39f7-11eb-9cc1-7fd2f6c6b172.png)

**Comment by hymanjd** [comment]
does this still occur with the current release?
