### ISSUE TITLE
How to run the pythonn example

### ISSUE THREAD

**Issue by xuhenry** [lanl/dfnWorks#13]
Dear all, 
    I have successfully installed the pydfnworks, but I don't known how to run the examples. There are some errors when I run the script:

~/OpenSource/dfnWorks/examples/pruning$ python3 run_prune_explicit_part1.py 
Error checking dfnworks_PATH
 is not a directory.
Please check the path in either pydfnworks/general/paths.py or .dfnworksrc.
Exiting

Is there anyone can help me ?
Thanks a lot!
Best regards, 
Henry

**Comment by hymanjd** [comment]
Hi Henry, 

Did you run fix_paths.py in pydfnworks/bin and correct your other paths in "pydfnworks/general/paths.py"?

Jeffrey

**Comment by xuhenry** [comment]
Hello Hymanjd,
  Yes I have ran fix_paths.py, and show

 :/home/xxxx/OpenSource
replacing  DUMMY  with  /home/xxxx/OpenSource

Thanks a lot!
Henry

**Comment by hymanjd** [comment]
Is that the correct path for your installation? What's in your paths.py file?

**Comment by WuHuiLLNL** [comment]
Hi, I am trying to use the pydfnworks package, and got similar problems as Henry mentioned. 
In "paths.py" where we should specify environment paths, there are several paths that I don't know how to set, such as PETSC_DIR, PETSC_ARCH, PFLOTRAN_EXE, LAGRIT_EXE and FEHM_EXE. Are these directories and executables already in the dfnworks or I have to install them by myself?

Thanks,
Hui

**Comment by hymanjd** [comment]
Hi Hui,

You have to install and build PETSC, LaGriT, PFLOTRAN, and FEHM. They do not come with the git version of dfnWorks. Once you install them, then you can add the paths. Alternatively, you can  create a .dfnworksrc in your home directory

However, they are precompiled with the docker container of the package

https://hub.docker.com/r/ees16/dfnworks

Jeffrey

**Comment by WuHuiLLNL** [comment]
@hymanjd 
Hi Jeffrey, thank you for the response. I will try the docker container then.
