### ISSUE TITLE
Isolated Fractures

### ISSUE THREAD

**Issue by alannahcb** [lanl/dfnWorks#14]
Hi dfnWorks Team,

I’d like to keep the isolated fractures not just the connected fractures, in order to combine them with a high permeability matrix.
However, when I set ‘keepIsolatedFractures' to 1, the code runs only up to —> Poisson sampling for fracture... 
But then returns the error starting with:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Backtrace for this error: 
….(a bunch of numbers)
Segmentation fault. 
—> ERROR occurred during meshing fracture 8

It continues to produce this error for a couple more rounds.

Any advice on how to keep isolated fractures in the model would be great. 
Thanks very much,
Alannah

**Comment by hymanjd** [comment]
Hi Alannah, 
If you are combining the fractures with a high permeability matrix using UDFM, you don't need to mesh the fractures using DFN.mesh_fractures(). 

You can run

DFN.map_to_continuum()
DFN.upscale()

If you still want to see the DFN, you can DFN.mesh_fractures(visual_mode=True)

**Comment by alannahcb** [comment]
Great thanks! I'll give that a go

**Comment by hymanjd** [comment]
@alannahcb Is this issue resolved?

**Comment by alannahcb** [comment]
Yes, the keepIsolatedFractures works with the latest version of dfnWorks and seems to run well with the UDFM

**Comment by alannahcb** [comment]
Thanks!
