### ISSUE TITLE
Running exemple on docker image

### ISSUE THREAD

**Issue by lperozzi** [lanl/dfnWorks#15]
Dear developers, first of all many thanks for your effort in developing a such interesting software.

I would like to use `dfnWorks` within a Docker image. I followed the instruction in `dfnWorks.pdf`to `pull`and `run`the latest image. Now I'm trying to reproduce the `faults` example but I have an error saying:

```
checking Input File

--> Copying input file: /dfnWorks/examples/faults/gen_faults.dat
Unable to copy dfnGen input file to working directory
/dfnWorks/examples/faults/gen_faults.dat
```

I run the dfnWorks Docker image with the following command:
`docker run -ti --name dfntest -v /Users/username/Documents/dfnWorks/examples:/dfnworks/work  ees16/dfnworks:latest`

I then run the `faults` example case with the following command:

`python examples/faults/run.py -name examples/test_fault -input examples/faults/fault_run_file.txt -ncpu 4`

that gives me the error mentioned above. Where I'm doing wrong?
Many thanks for your help
Lorenzo

**Comment by hymanjd** [comment]
Hi Lorenzo,

You need to change the name of the mounted volume to a path on your computer.  I'm guessing that the following:

/Users/username/Documents/dfnWorks/examples

isn't on your machine and that username should be your account name.  Give that a whirl and let us know if it works.

Jeffrey

**Comment by lperozzi** [comment]
Hi @hymanjd 

many thanks for the prompt reply. Actually, I was setting an existing local folder. The problem, was, apparently that: `-name examples/test_fault`. If I change it with  `-name /test_fault` it does work. 
So, many thanks again I can now explore all the features/examples of dfnWorks.
Lorenzo
