### ISSUE TITLE
Running dfnWorks example with native build

### ISSUE THREAD

**Issue by KALEEMULLAHJANKHAN** [lanl/dfnWorks#19]
Hello everyone,

I have successfully compiled dfnWorks with all the dependencies and now facing problem to run its example. I have already fixed all the paths. How can I overcome with this issue?

Secondly,

I also want to know about to mount a volume in docker. I have installed docker on my ubuntu 20.04 and pulled the docker image with "sudo" and now cant mount the volume. I am attaching the terminal errors for reference.

![image](https://user-images.githubusercontent.com/89472468/160545536-5047a235-e404-45bd-a7b2-d770ebfaa018.png)

![image](https://user-images.githubusercontent.com/89472468/160545631-01cfa5a5-b857-48ab-b7d0-6c0bd961e0a1.png)

**Comment by hymanjd** [comment]
@KALEEMULLAHJANKHAN I don't understand your first question. Can you please be more specific? have you followed all the instructions on this page

https://dfnworks.lanl.gov/setup.html

This also contains information about mounting volumes.
