### ISSUE TITLE
User defined ellipses and using dip/strike

### ISSUE THREAD

**Issue by muellerchr** [lanl/dfnWorks#21]
I have some problems generating user defined ellipses and using the dip/strike option. As a basis I used the example "4_user_defined_ell_uniform" (that works fine) and changed the relevant lines in the UserEll_Input_File. I modified userOrientationOption = 2 and add a line Dip_Strike with the corresponding values ({60,90} as a example). It seems that the variable "Normal" is still required although userOrientationOption was changed to 2 (Variable not found: "Normal:" ERROR! Generation failed). What am I doing wrong and how can I generate user defined fractures with dip/strike values.

Thanks for the effort to develop such a great tool!
Christian

**Comment by hymanjd** [comment]
Can you send me your input files (jhyman@lanl.gov)

**Comment by hymanjd** [comment]
@muellerchr I pushed a patch to the repo. Please pull, recompile DFNGen, and try again. Also, change 

/*****************************************************************************/
// user Orientation Option 
//	0 - Normal Vector -> Normal {x,y,z}
//	1 - Trend / Plunge -> Trend_Plunge {trend, plunge} -> Must be degrees
//  2 - Dip / Strike - > Dip_Strike {dip, strike} -> Must be degrees
/*****************************************************************************/


to

/*****************************************************************************/
// user Orientation Option 
//	0 - Normal Vector -> Normal {x,y,z}
//	1 - Trend / Plunge -> Trend_Plunge {trend, plunge} -> Must be degrees
//  2 - Dip / Strike - > Dip_Strike {dip, strike} -> Must be degrees
/*****************************************************************************/
