### ISSUE TITLE
dfnWorks on Docker: Input file not found

### ISSUE THREAD

**Issue by sandrotruttmann** [lanl/dfnWorks#25]
Hi there,

I have an issue with running dfnWorks v2.2 on my MacBook, using the Docker Container. I am not able to run the test examples (e.g. here the 'faults' example). I tried the following:

1) Start dfnWorks on Docker in the Terminal:
`docker run -ti --name dfnWorks_TEST -v /Users/username/Downloads/dfnWorks/examples:/dfnWorks/work ees16/dfnworks:latest`

2) Run dfnWorks from the Terminal:
`python examples/faults/run.py -name /faults_test -input examples/faults/fault_run_file.txt `

3) dfnWorks then successfully starts, but prints the following output:
>================================================================================
> --> Creating DFN class
> --> Jobname:  /faults_test2
> --> Number of cpus requested:  4
> --> Reading Input from examples/faults/fault_run_file.txt
> --> dfnGen input file:  /dfnWorks/dfnworks-main/examples/faults/gen_faults.dat
> --> dfnFlow input file:  /none/
> --> dfnTrans input file:  /none/
> 
> --> Creating DFN class: Complete
> ================================================================================
> 
> Current directory is now: /faults_test2
> Jobname is /faults_test2
> 
> ================================================================================
> Checking Input File
> 
> Input file 
> /dfnWorks/dfnworks-main/examples/faults/gen_faults.dat not found
>  Exiting# # 

My "fault_run_file.txt" file contains the following:
dfnGen /Users/username/Downloads/dfnworks/examples/faults/gen_faults.dat
dfnFlow /none/
dfnTrans /none/

It is saved in the same folder as the other example files on `/Users/username/Downloads/dfnWorks/examples/faults`

What I don't understand is the path of the error message, which starts with '/dfnWorks/dfnworks-main/...' which I cannot find on my computer. I guess there is something wrong with the path I selected, but I couldn't figure out what was the issue.
What am I doing wrong?

**Comment by hymanjd** [comment]
Hi Scott,


It looks like the path is incorrect in the run file name. Change that to


/dfnWorks/dfnworks-main/examples/faults/gen_faults.dat


______________________________________
Jeffrey Hyman
Computational Earth Science (EES-16)
Los Alamos National Laboratory
1 - (505) - 665 - 2074
***@***.***
________________________________
From: Sandro Truttmann ***@***.***>
Sent: Friday, April 29, 2022 12:52:32 AM
To: lanl/dfnWorks
Cc: Subscribed
Subject: [EXTERNAL] [lanl/dfnWorks] dfnWorks on Docker: Input file not found (Issue #25)


Hi there,

I have an issue with running dfnWorks v2.2 on my MacBook, using the Docker Container. I am not able to run the test examples (e.g. here the 'faults' example). I tried the following:

  1.  Start dfnWorks on Docker in the Terminal:
docker run -ti --name dfnWorks_TEST -v /Users/username/Downloads/dfnWorks/examples:/dfnWorks/work ees16/dfnworks:latest

  2.  Run dfnWorks from the Terminal:
python examples/faults/run.py<https://urldefense.com/v3/__http://run.py__;!!Bt8fGhp8LhKGRg!VnQ-mteXCsWsGwcYcP-kQWA1s9VwBAqcVOV-YWBGwXU65E1Qz59y7Vxz9sSZtlQ$> -name /faults_test -input examples/faults/fault_run_file.txt

  3.  dfnWorks then successfully starts, but prints the following output:

================================================================================
--> Creating DFN class
--> Jobname: /faults_test2
--> Number of cpus requested: 4
--> Reading Input from examples/faults/fault_run_file.txt
--> dfnGen input file: /dfnWorks/dfnworks-main/examples/faults/gen_faults.dat
--> dfnFlow input file: /none/
--> dfnTrans input file: /none/

--> Creating DFN class: Complete

Current directory is now: /faults_test2
Jobname is /faults_test2

================================================================================
Checking Input File

Input file
/dfnWorks/dfnworks-main/examples/faults/gen_faults.dat not found
Exiting# #

My "fault_run_file.txt" file contains the following:
dfnGen /Users/username/Downloads/dfnworks/examples/faults/gen_faults.dat
dfnFlow /none/
dfnTrans /none/

It is saved in the same folder as the other example files on /Users/username/Downloads/dfnWorks/examples/faults

What I don't understand is the path of the error message, which starts with '/dfnWorks/dfnworks-main/...' which I cannot find on my computer. I guess there is something wrong with the path I selected, but I couldn't figure out what was the issue.
What am I doing wrong?

**Comment by hymanjd** [comment]
Hi Sandro,

Please update to the current version, that should correct most of the path name issues. It looks like the faults paths need to be updated in the container.  We will address this in the next release. in the meantime, you can modify the paths in the fault run files to those in the virtual machine.
Jeffrey



______________________________________
Jeffrey Hyman
Computational Earth Science (EES-16)
Los Alamos National Laboratory
1 - (505) - 665 - 2074
***@***.***
________________________________

**Comment by sandrotruttmann** [comment]
Hi Jeffrey,
thanks for your fast reply. However, I don't figure out how I can update to v2.5 in Docker... Is it right that the Docker image does not come with the newest version (2.5) of dfnWorks?
/Sandro

**Comment by hymanjd** [comment]
The current image is v2.5.3 and should be labeled at latest.



[signature_61897647]

Jeffrey D. Hyman
Staff Scientist
Computational Earth Science (EES-16)
Los Alamos National Laboratory
https://dfnworks.lanl.gov/
Pronouns: he, him, his
Office: +1 (505) 665-2074



From: Sandro Truttmann ***@***.***>
Reply-To: lanl/dfnWorks ***@***.***>
Date: Monday, May 2, 2022 at 9:28 AM
To: lanl/dfnWorks ***@***.***>
Cc: Jeffrey Hyman ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [lanl/dfnWorks] dfnWorks on Docker: Input file not found (Issue #25)


Hi Jeffrey,
thanks for your fast reply. However, I don't figure out how I can update to v2.5 in Docker... Is it right that the Docker image does not come with the newest version (2.5) of dfnWorks?
/Sandro

**Comment by sandrotruttmann** [comment]
Hi Jeffrey,
I was already using image v2.5.3 (latest), was just confused by the print in the terminal which stated "Program: DFNWorks  V2.2". 
However, I'm still not able to run dfnWorks via Docker. I really don't understand the issue... 
What is also weird is that the usual command for running dfnWorks, e.g. 
`python run.py -name /dfnWorks/work/4_user_rects_example -input 4_user_defined_rectangles_run_file.txt` is not working with a simple `run.py` command, but only when choosing the absolute path for the run.py file on my machine (e.g. `../dfnWorks/examples/faults/run.py`). Could it be that I mounted the volume in a wrong way?
/Sandro

**Comment by hymanjd** [comment]
That’s a possibility. What’s you command mounting the volume? Also, please email me directly to sort this out and then we can post the resolution to github.

J



[signature_61897647]

Jeffrey D. Hyman
Staff Scientist
Computational Earth Science (EES-16)
Los Alamos National Laboratory
https://dfnworks.lanl.gov/
Pronouns: he, him, his
Office: +1 (505) 665-2074



From: Sandro Truttmann ***@***.***>
Reply-To: lanl/dfnWorks ***@***.***>
Date: Tuesday, May 3, 2022 at 2:47 AM
To: lanl/dfnWorks ***@***.***>
Cc: Jeffrey Hyman ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [lanl/dfnWorks] dfnWorks on Docker: Input file not found (Issue #25)


Hi Jeffrey,
I was already using image v2.5.3 (latest), was just confused by the print in the terminal which stated "Program: DFNWorks V2.2".
However, I'm still not able to run dfnWorks via Docker. I really don't understand the issue...
What is also weird is that the usual command for running dfnWorks, e.g.
python run.py<https://urldefense.com/v3/__http:/run.py__;!!Bt8fGhp8LhKGRg!RQHux1cKFZrkhphZCnM4l0pxUtn5WCgtZGe7IPQ6i2lEiZjfA1zg5HBm6Zgl8As$> -name /dfnWorks/work/4_user_rects_example -input 4_user_defined_rectangles_run_file.txt is not working with a simple run.py<https://urldefense.com/v3/__http:/run.py__;!!Bt8fGhp8LhKGRg!RQHux1cKFZrkhphZCnM4l0pxUtn5WCgtZGe7IPQ6i2lEiZjfA1zg5HBm6Zgl8As$> command, but only when choosing the absolute path for the run.py<https://urldefense.com/v3/__http:/run.py__;!!Bt8fGhp8LhKGRg!RQHux1cKFZrkhphZCnM4l0pxUtn5WCgtZGe7IPQ6i2lEiZjfA1zg5HBm6Zgl8As$> file on my machine (e.g. ../dfnWorks/examples/faults/run.py<https://urldefense.com/v3/__http:/run.py__;!!Bt8fGhp8LhKGRg!RQHux1cKFZrkhphZCnM4l0pxUtn5WCgtZGe7IPQ6i2lEiZjfA1zg5HBm6Zgl8As$>). Could it be that I mounted the volume in a wrong way?
/Sandro

**Comment by hymanjd** [comment]
Sandro,


I just pushed the v2.6 container. Pull and try again. Let me know if that resolved the issue.


J

______________________________________
Jeffrey Hyman
Computational Earth Science (EES-16)
Los Alamos National Laboratory
1 - (505) - 665 - 2074
***@***.***
________________________________

**Comment by sandrotruttmann** [comment]
Hi Jeffrey

I pulled the v2.6 container and the path issue has been resolved - thanks a lot!
So dfnWorks runs fine now, but when I run e.g. the faults example it creates a new folder with attached empty folders an an exe file. However, I don't find any output as specified in the terminal (mesh etc.). Am I overlooking that, or is that another bug? I attached you the folder created by the test run in this mail.

Generally, I do the following:

# 1) Run Docker
docker run -ti --name dfntest -v /Users/sandrotruttmann/Desktop/DFN/:/dfnWorks/work ees16/dfnworks:latest

# 2) Run dfnWorks

python ../dfnWorks/examples/faults/run.py -name faults_test -input ../dfnWorks/examples/faults/fault_run_file.txt -ncpu 4

Thanks a lot for your support!
Cheers,
Sandro




Am 03.05.2022 um 18:35 schrieb Jeffrey Hyman ***@***.******@***.***>>:


Sandro,


I just pushed the v2.6 container. Pull and try again. Let me know if that resolved the issue.


J

______________________________________
Jeffrey Hyman
Computational Earth Science (EES-16)
Los Alamos National Laboratory
1 - (505) - 665 - 2074
***@***.***
________________________________
