### ISSUE TITLE
Pflotran mesh error

### ISSUE THREAD

**Issue by peterae** [lanl/dfnWorks#26]
I noticed that when using large domains (> 100 m) the PFLOTRAN simulation (as part of dfnWorks) crashes with the following error:

 ERROR(1): Coincident cell and face centroids found in UGridExplicitSetBoundaryConnect() for region "inflow".  See details above.
 (2): Coincident cell and face centroids found at (1.250000000E+02, 1.250000000E+02,-6.250000000E+00) 
...

This error seems to be related to fact that the epsilon (= self.h * 10**-3) used to offset the boundary *ex nodes is small in comparison to the dimension of the domain such that the epsilon does to show up in the coordinates of the ex files. One solution to this would be to change the print format in the source by adding 1 or 2 more decimals to the scientific notation of the coordinates.

Peter

**Comment by hymanjd** [comment]
This was fixed with the commit 2085ed91241372de46e0d015d36c06518048035a
