### ISSUE TITLE
Unable to copy dfnGen input file

### ISSUE THREAD

**Issue by yihaoFu** [lanl/dfnWorks#3]
Hi,

I have recently update the dfnWorks from 2.1 to 2.2, and installation was done without any issue (I think).

However when I run the test example (for example, 4_user_defined rects) using the command below:
`python run.py -name /home/yihao/Project/dfnWorks/examples/4_user_rects/test_output_files/ -input /home/yihao/Project/dfnWorks/examples/4_user_rects/4_user_defined_rectangles_run_file.txt -ncpu 4`

the error message pop up saying: 
ERROR: dfnGen input file path:  _/home/yihao/Project/dfnWorks/examples/4_user_rects/test_output_files/dfnWorks/examples/4_user_rects/gen_4_user_rectangles.dat does not exit.
Unable to copy dfnGen input file_

I guess something wrong with pointing to the correct path?

Thanks,

YIHAO

**Comment by hymanjd** [comment]
Hi Yihao,
I'm guessing that your path to the generation file (gen_4_user_rectangles.dat) is in the working dir, so it can't copy over itself. Try moving your files in *_run_file.txt into a different dir and then give it a whirl. 

Can you post your /home/yihao/Project/dfnWorks/examples/4_user_rects/4_user_defined_rectangles_run_file.txt  as well?

J

**Comment by yihaoFu** [comment]
Thanks very much for your help and sorry for the late reply.

My file structure is like this:

_/home/yihao/geoProject/dfnWorks/test_output_files/*_run_file.txt_

Other model input data are in the folder 

`/home/yihao/geoProject/dfnWorks/examples/4_user_rects/.....`
When I run the command:

`python run.py -name /home/yihao/geoProject/dfnWorks/test_output_files -input /home/yihao/geoProject/dfnWorks/examples/4_user_rects/4_user_defined_rectangles_run_file.txt`

It shows me this error:

```
Jobname is /home/yihao/geoProject/dfnWorks/test_output_files/
ERROR: dfnGen input file path: /dfnWorks/examples/4_user_rects/gen_4_user_rectangles.dat does not exist
/dfnWorks/examples/4_user_rects/gen_4_user_rectangles.dat 
Unable to copy dfnGen input file
/dfnWorks/examples/4_user_rects/gen_4_user_rectangles.dat
Exiting
```
My *_run_file.txt* has been [uploaded.]
[4_user_defined_rectangles_run_file.txt](https://github.com/lanl/dfnWorks/files/3562413/4_user_defined_rectangles_run_file.txt)

I am not sure if this file looks for the relative path?

Because if I change the file, for example:
from
`dfnGen /dfnWorks/examples/4_user_rects/gen_4_user_rectangles.dat
`to
`/home/yihao/geoProject/dfnWorks/examples/4_user_rects/gen_4_user_rectangles.dat
`
The error message would say:
`dfnGen input file path: /home/yihao/geoProject/dfnWorks/test_output_files/home/yihao/geoProject/dfnWorks/examples/4_user_rects/gen_4_user_rectangles.dat does not exist.`

Does it mean I have to put the folder which contains all input data, one level below the output file folder?

Thanks,

YIHAO

**Comment by hymanjd** [comment]
Hi Yihao,

You need to use absolute paths in the file names in run_file.txt and correct it to the file location. For example, you have /home/ twice in 

/home/yihao/geoProject/dfnWorks/test_output_files/home/yihao/geoProject/dfnWorks/examples/4_user_rects/gen_4_user_rectangles.dat

Which is incorrect. 

J

**Comment by yihaoFu** [comment]
The problem has been solved, thanks very much!

**Comment by yihaoFu** [comment]
The issue has been solved, much appreciated!

**Comment by hymanjd** [comment]
Glad to hear it.
