### ISSUE TITLE
A tiny typo in README

### ISSUE THREAD

**Issue by n2uts** [lanl/dfnWorks#42]
Totally harmless, but in README [python section](https://github.com/lanl/dfnWorks/blob/master/README.md#python)，`networkx` shown twice, I believe one of them should be `mplstereonet`.Maybe a `pip freeze > deps.txt` from docker container can be added to README?

```python
pip install numpy h5py scipy networkx fpdf matplotlib mplstereonet seaborn multiprocess
```

I wrote a simple instruction for setting up dfnWorks v2.5 early this year in [lark](https://www.yuque.com/turna/gwbooklet/oere21) (a notion-like note-taking software), though it's not written in English, it should not affect understanding of the notes. While I personally suggesting writing about `.dfnworksrc` as follows:

```bash
cd ~ && touch .dfnworksrc
echo '{  
    "dfnworks_PATH": "dfnworks_path",
    "PETSC_DIR": "petsc_path",
    "PETSC_ARCH": "petsc_arch_name",
    "PFLOTRAN_EXE": "pflotran_exe_path",
    "PYTHON_EXE": "python_exe_path",
    "LAGRIT_EXE": "lagrit_exe_path",   
    "FEHM_EXE": "fehm_exe_path"
}' >> .dfnworksrc

# PFLOTRAN executable path and it's environment variable
sed -i "s|pflotran_exe_path|$PFLOTRAN_DIR/src/pflotran/pflotran|g" ~/.dfnworksrc
sed -i "s|petsc_path|$PETSC_DIR|g" ~/.dfnworksrc && sed -i "s|petsc_arch_name|$PETSC_ARCH|g" ~/.dfnworksrc
````

**Comment by hymanjd** [comment]
Thanks! I updated the README.md!
