### ISSUE TITLE
Can I establish curved fractures mesh ?

### ISSUE THREAD

**Issue by Beniuy** [lanl/dfnWorks#43]
In the examples, I have learned several examples about plane fractures. I wonder if DFN can establish curved fractures and conduct numerical simulation to calculate water pressure ? Could you give me some advice on it ? Thanks!

**Comment by Beniuy** [comment]
Thanks for your prompt advice.  Is the existing code still applicable to user-defined curved surface with planes? I mean just setting the input file about fractures without inserting new codes.

**Comment by hymanjd** [comment]
Yes, but it would be complicated
From: Xu Yue ***@***.******@***.***>>
Date: Friday, Jan 06, 2023 at 6:09 PM
To: lanl/dfnWorks ***@***.******@***.***>>
Cc: Hyman, Jeffrey De'Haven ***@***.******@***.***>>, Comment ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [lanl/dfnWorks] Can I establish curved fractures mesh ? (Issue #43)


Thanks for your prompt advice. Is the existing code still applicable to user-defined curved surface with planes? I mean just setting the input file about fractures without inserting new codes.

**Comment by Beniuy** [comment]
Thanks a lot!
