### ISSUE TITLE
How to define triple intersections?

### ISSUE THREAD

**Issue by Beniuy** [lanl/dfnWorks#49]
Hi,
I want to define a triple intersection, but it shows that

> Rejected User Defined Polygon Fracture (Defined By Coordinates) 2
        rejectCode = -6: Fracture too close to another fracture's edge.
Or
> Rejected User Defined Polygon Fracture (Defined By Coordinates) 3
        rejectCode = -12: Fracture created a triple intersection with an angle too small.

How to avoid the two aforementioned error ? 
My polygons.dat is 
```
nPolygons: 3
4 {-4,0,-1} {-4,0,1}  {4,0,1}  {4,0,-1} 
4 {-4,-1,-1} {-4,-1,1} {-2.9,0.1,1} {-2.9,0.1,-1}
4 {-4,1,-1} {-4,1,1} {-2.9,-0.1,1} {-2.9,-0.1,-1}
```
with domain size {8,10,4}.    [This is modified from the example user_polygons]

Best regards

**Comment by hymanjd** [comment]
It appears that your fractures are not acceptable with your fram parameter h, what is that value?

**Comment by Beniuy** [comment]
Thank you ! I set the 'h' small enough compared with the fracture size, but it seems that the two edges can't be collinear. Here is a picture for reference. Can I make the three edges collinear? 
![image](https://user-images.githubusercontent.com/50405929/217417048-9e43d39e-5f2b-4e70-91e5-f4b6c142a6f7.png)

**Comment by hymanjd** [comment]
I"m guessing that your top edge is the issue. Try running with disableFram : True and visualmode to look at it closer in paraview

**Comment by Beniuy** [comment]
Thanks for your advice！ I set the disableFram true, and the multiple fractures are not rejected now. But it says cannot find uge file ?
![image](https://user-images.githubusercontent.com/50405929/217713291-17187393-5687-4be7-84f9-3aad7ce42012.png)
Tips :
My purpose is construct a model like this, it has triple intersections.
![image](https://user-images.githubusercontent.com/50405929/217713854-f38590aa-269b-40a0-8123-282fa4ca87fb.png)

My polygon file is as follow

> nPolygons: 5
4 {-1.0,0,-1} {-1.0,0,1}  {+1.0,0,1}  {+1.0,0,-1} 
4 {-2,-1,-1} {-2,-1,1} {-1,0.0,1} {-1,0.0,-1}
4 {-2,1,-1} {-2,1,1} {-1.0,-0.0,1} {-1.0,-0.0,-1}
4 {+2,-1,-1} {+2,-1,1} {+1, 0,1} {+1,0,-1}
4 {+2,1,-1} {+2,1,1} {+1.,-0.0,1} {+1.,-0.0,-1}

**Comment by hymanjd** [comment]
If you run with disable fram, it will not create a uge file, and you can’t run flow. This is just for visualization.

I’d suggest extending your polygon edges a little past the intersections. This might fix your problem.


[signature_61897647]

Jeffrey D. Hyman
Staff Scientist
Energy and Natural Resources Security (EES-16)
Los Alamos National Laboratory
https://dfnworks.lanl.gov/
Pronouns: he, him, his
Office: +1 (505) 665-8737




From: Xu Yue ***@***.***>
Reply-To: lanl/dfnWorks ***@***.***>
Date: Wednesday, February 8, 2023 at 8:54 PM
To: lanl/dfnWorks ***@***.***>
Cc: Jeffrey Hyman ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [lanl/dfnWorks] How to define triple intersections? (Issue #49)


Thanks for your advice！ I set the disableFram true, and the multiple fractures are not rejected now. But it says cannot find uge file ?
[Image removed by sender. image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/50405929/217713291-17187393-5687-4be7-84f9-3aad7ce42012.png__;!!Bt8fGhp8LhKGRg!D6_qcnLnPcuq5I-kSv1NOuv-RhX2VFivv2CEq_ZbulUHTvy0STr-AhAyO_uWmhizpmCfukNb4t-_oispq5-vCzpw$>
Tips :
My purpose is construct a model like this, it has triple intersections.
[Image removed by sender. image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/50405929/217713854-f38590aa-269b-40a0-8123-282fa4ca87fb.png__;!!Bt8fGhp8LhKGRg!D6_qcnLnPcuq5I-kSv1NOuv-RhX2VFivv2CEq_ZbulUHTvy0STr-AhAyO_uWmhizpmCfukNb4t-_oispq0g3NOnt$>

My polygon file is as follow

nPolygons: 5
4 {-1.0,0,-1} {-1.0,0,1} {+1.0,0,1} {+1.0,0,-1}
4 {-2,-1,-1} {-2,-1,1} {-1,0.0,1} {-1,0.0,-1}
4 {-2,1,-1} {-2,1,1} {-1.0,-0.0,1} {-1.0,-0.0,-1}
4 {+2,-1,-1} {+2,-1,1} {+1, 0,1} {+1,0,-1}
4 {+2,1,-1} {+2,1,1} {+1.,-0.0,1} {+1.,-0.0,-1}

**Comment by Beniuy** [comment]
Thank you very much ！ I am really grateful for your prompt advice ！
