### ISSUE TITLE
About flow condition ? 

### ISSUE THREAD

**Issue by Beniuy** [lanl/dfnWorks#50]
DFN can set Dirichlet boundary conditions. I wonder if Newman boundary conditions can be set? For example, I want to set the 'source term' or flow rate boundary conditions at the boundary instead of water pressure. 
Thank you very much !
Best regards

**Comment by hymanjd** [comment]
Please see the instructions for flow_condition on the pflotran website 

https://www.pflotran.org/documentation/user_guide/cards/subsurface/flow_condition_card.html

Any of those can be used in the DFN

**Comment by Beniuy** [comment]
Thanks for your help !
