### ISSUE TITLE
More than one initial condition defined

### ISSUE THREAD

**Issue by Chuanyao-Zhong** [lanl/dfnWorks#6]
Dear Sir/Madam,

When I was playing with the example case: 4_user_rects, I wanted to change the 'PARTICLES INITIAL POSITIONS' in the PTDFN_control.dat file, so I changed the "init_nf" from 'yes' to "no", then I set the "init_random" (all particles are placed randomly over all fracture surface, not only on boundary edges) to be "yes".
However, it gave me this error:

--> Checking Initial Conditions
ERROR!!! More than one initial condition defined
Exiting
Selected Initial Conditions:
:
init_random:
init_random:

I have checked that I turned off all the other intial conditions in the PARTICLES INITIAL POSITIONS section, and I didn't make any changes in other places.
So I am wondering why it said "More than one initial condition defined", and how could I solve this problem?

Thank you!

Kindest regards,
Chuanyao

The error:
![Capture1](https://user-images.githubusercontent.com/56650438/76429793-287fa980-6375-11ea-94a3-3dfed183cfb9.JPG)

PARTICLES INITIAL POSITIONS:
![Capture2](https://user-images.githubusercontent.com/56650438/76429841-37fef280-6375-11ea-8cbc-4d8dfc974852.JPG)

**Comment by hymanjd** [comment]
Thank you for the post. I have reproduced the error and will work on fixing it.

**Comment by Chuanyao-Zhong** [comment]
Hello Jeffrey,

Ok! Thanks!

Kindest regards,
Chuanyao

**Comment by hymanjd** [comment]
Hi Chuanyao, 

Sorry for the long delay. We pushed an update that addresses this bug. Are you using the native build or Docker?

Jeffrey

**Comment by Chuanyao-Zhong** [comment]
Hello Jeffrey,

Thank you! I am currently using Docker to run dfnWorks.

Best regards,
Chuanyao

**Comment by hymanjd** [comment]
We haven't pushed the new container yet. I'm going to close this issue, but I'll let you know when we update the docker container.

**Comment by hymanjd** [comment]
I’ll be updating the docker container tonight. I’ll email you when I do.

--
Jeffrey Hyman PhD
https://dfnworks.lanl.gov/
Earth & Environmental Sciences Division (EES-16)
Los Alamos National Laboratory
Office: +1 (505) 665 2074

**Comment by Chuanyao-Zhong** [comment]
OK! Thank you so much!

Best regards,
Chuanyao

**Comment by hymanjd** [comment]
Container updated.  Pull and give it a shot.


J



______________________________________
Jeffrey Hyman
Computational Earth Science (EES-16)
Los Alamos National Laboratory
1 - (505) - 665 - 2074
jhyman@lanl.gov
________________________________

**Comment by Chuanyao-Zhong** [comment]
Great! Thank you, Jeffrey!

Best regards,
Chuanyao
