### ISSUE TITLE
help with paths

### ISSUE THREAD

**Issue by Ericadp1992** [lanl/dfnWorks#70]
Hello, and first of all thanks for sharing dfnWorks!

We are trying to install on Ubuntu (running as Windows Subsystem for Linux, but this should not be relevant).

We have cloned the repo, installed required libraries, compiled, and we have set variables in /home/<user>/.bashrc as follows:

```
export PETSC_DIR=/home/erica/petsc
export PETSC_ARCH=gnu-c-debug
export dfnworks_PATH=/home/erica/dfnWorks
export PFLOTRAN_EXE=/home/erica/pflotran/src/pflotran/pflotran
export PYTHON_EXE=/usr/bin/python3
export LAGRIT_EXE=/home/erica/LaGriT/build/lagrit
export FEHM_EXE=/home/erica/FEHM/src/xfehm_v3.3.1
export DFNGEN_EXE=home/erica/.local/lib/python3.10/site-packages/pydfnworks/dfnGen
```

The last line was added since running examples we get an error related to not finding the DFNGEN_EXE key, but we are probably using the wrong path, since now we get

```
--> Running DFNGEN
Running:
>>home/erica/.local/lib/python3.10/site-packages/pydfnworks/dfnGen dfnGen_output/output_dfnGen_input_clean.dat /home/erica/dfnWorks/examples/4_user_rects/output
/bin/sh: 1: home/erica/.local/lib/python3.10/site-packages/pydfnworks/dfnGen: not found
Error. Unable to find 'params.txt' in current directory <built-in function getcwd>.
```

Could you please help us setting the path?

We feel that everything else is OK since it actually starts running the workflow.

Thanks!

**Comment by hymanjd** [comment]
Hi Erica, 
You should be setting these paths in ~/.dfnworksrc not in your ~/.bashrc. Please see in the instructions here 

https://github.com/lanl/dfnWorks#set-the-lagrit-petsc-pflotran-python-and-fehm-paths
