### ISSUE TITLE
Installation information

### ISSUE THREAD

**Issue by gbene** [lanl/dfnWorks#71]
Hi all! 

Fist of all thanks for creating this fantastic piece of software. I've just installed it and find it very promising! 

For now I am manly interested in dfn generation (dfnGen) and so I wanted to know if to successfully build the pydfnworks package it is necessary that all the dependencies are met or if it possible to install only the dependencies related to the generation step (i.e. mainly LaGrit if I am not mistaken). 
I also was curious if the generation module is independent from the rest or there are functions and dependencies that are taken from the dfnFlow/Trans/Graph modules and dependency pool. 

Thanks in advance!

**Comment by hymanjd** [comment]
Hello, 
For dfn generation all you need is dfnGen, pydfnworks, and LaGrit. 
Thanks, J

**Comment by gbene** [comment]
Thank you!
