### ISSUE TITLE
Docker container-change python scripts of pydfnWorks Package

### ISSUE THREAD

**Issue by yingtaohu** [lanl/dfnWorks#84]
When I use Docker container to run dfnworks, the running files in the bin directory can be easily changed by copying files from my machine, but how can I change the python scripts of pydfnWorks Package in the pydfnworks folder?

![C59F2F87-A5BF-4362-9EB8-6181E98F4FFD](https://github.com/lanl/dfnWorks/assets/34232470/33165899-2a3f-4e97-95c7-25a33029286d)
![DDE7996C-0D3C-4245-969A-F949D575C839](https://github.com/lanl/dfnWorks/assets/34232470/5731d2da-f266-4fc2-9be3-7d4242b96c1a)

Best regards,
Yingtao Hu

**Comment by hymanjd** [comment]
Hello,

You cannot change the source files in the docker container. You’ll need to do a native build to modify those.

Jeffrey


From: yingtaohu ***@***.***>
Reply-To: lanl/dfnWorks ***@***.***>
Date: Wednesday, July 3, 2024 at 2:07 AM
To: lanl/dfnWorks ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [lanl/dfnWorks] Docker container-change python scripts of pydfnWorks Package (Issue #84)


When I use Docker container to run dfnworks, the running files in the bin directory can be easily changed by copying files from my machine, but how can I change the python scripts of pydfnWorks Package in the pydfnworks folder?

C59F2F87-A5BF-4362-9EB8-6181E98F4FFD.png (view on web)<https://urldefense.com/v3/__https:/github.com/lanl/dfnWorks/assets/34232470/33165899-2a3f-4e97-95c7-25a33029286d__;!!Bt8fGhp8LhKGRg!DNr9xscMwcvmF4uML__7tn47BzYCFzh7DU9TWEntKwneY8QQyZamtxDjaFOQQOGziVgUy28JjowZbAvouCQp7EaS$>
DDE7996C-0D3C-4245-969A-F949D575C839.png (view on web)<https://urldefense.com/v3/__https:/github.com/lanl/dfnWorks/assets/34232470/5731d2da-f266-4fc2-9be3-7d4242b96c1a__;!!Bt8fGhp8LhKGRg!DNr9xscMwcvmF4uML__7tn47BzYCFzh7DU9TWEntKwneY8QQyZamtxDjaFOQQOGziVgUy28JjowZbAvouFQkxh2V$>

Best regards,
Yingtao Hu

**Comment by yingtaohu** [comment]
I got it, thanks, Jeffrey.
